# Adaptable networking/services; no mandatory Steam SDK or downloads at configure time.
option(FORGE_WITH_NETWORKING "Build independent ENet LAN transport" ON)
option(FORGE_WITH_GNS "Build Valve open-source GameNetworkingSockets IP transport" OFF)
option(FORGE_WITH_STEAMWORKS "Build official Steamworks platform and sockets" OFF)
set(FORGE_STEAMWORKS_SDK "" CACHE PATH "User-owned Steamworks SDK root (contains public/steam)")
add_library(forge_network STATIC engine/src/network.cpp engine/src/steam.cpp)
target_include_directories(forge_network PUBLIC "${CMAKE_CURRENT_SOURCE_DIR}/engine/include" "${CMAKE_CURRENT_SOURCE_DIR}/vendor")
if(WIN32)
  target_compile_definitions(forge_network PRIVATE NOMINMAX WIN32_LEAN_AND_MEAN)
endif()
target_link_libraries(forge_network PUBLIC Threads::Threads)
target_compile_definitions(forge_network PUBLIC FORGE_WITH_NETWORKING=$<BOOL:${FORGE_WITH_NETWORKING}> FORGE_WITH_GNS=$<BOOL:${FORGE_WITH_GNS}> FORGE_WITH_STEAMWORKS=$<BOOL:${FORGE_WITH_STEAMWORKS}>)
if(FORGE_WITH_NETWORKING)
  if(NOT EXISTS "${CMAKE_CURRENT_SOURCE_DIR}/vendor/enet/CMakeLists.txt")
    message(FATAL_ERROR "Run python tools/dependencies.py for ENet")
  endif()
  add_subdirectory(vendor/enet EXCLUDE_FROM_ALL)
  target_include_directories(enet PUBLIC "${CMAKE_CURRENT_SOURCE_DIR}/vendor/enet/include")
  if(WIN32)
    target_link_libraries(enet PUBLIC ws2_32 winmm)
  endif()
  target_sources(forge_network PRIVATE engine/src/network_lan.cpp)
  target_link_libraries(forge_network PUBLIC enet)
endif()
if(FORGE_WITH_GNS OR FORGE_WITH_STEAMWORKS)
  target_sources(forge_network PRIVATE engine/src/network_port.cpp)
  if(WIN32)
    target_link_libraries(forge_network PUBLIC ws2_32)
  endif()
endif()
if(FORGE_WITH_GNS)
  if(NOT EXISTS "${CMAKE_CURRENT_SOURCE_DIR}/vendor/gns/CMakeLists.txt")
    message(FATAL_ERROR "Run python tools/dependencies.py --sockets; install Protobuf and OpenSSL (macOS/Linux)")
  endif()
  set(Protobuf_USE_STATIC_LIBS ON CACHE BOOL "Use static Protobuf for portable networking packages")
  set(OPENSSL_USE_STATIC_LIBS TRUE CACHE BOOL "Use static OpenSSL for portable networking packages")
  if(WIN32 AND NOT Protobuf_USE_STATIC_LIBS)
    message(FATAL_ERROR "Forge Windows socket packaging requires static Protobuf; use tools/network_dependencies.py")
  endif()
  set(BUILD_STATIC_LIB ON CACHE BOOL "" FORCE)
  set(BUILD_SHARED_LIB OFF CACHE BOOL "" FORCE)
  set(BUILD_EXAMPLES OFF CACHE BOOL "" FORCE)
  set(BUILD_TESTS OFF CACHE BOOL "" FORCE)
  set(BUILD_TOOLS OFF CACHE BOOL "" FORCE)
  set(ENABLE_ICE OFF CACHE BOOL "" FORCE)
  set(USE_STEAMWEBRTC OFF CACHE BOOL "" FORCE)
  if(WIN32)
    set(USE_CRYPTO BCrypt CACHE STRING "" FORCE)
  else()
    set(USE_CRYPTO OpenSSL CACHE STRING "" FORCE)
  endif()
  add_subdirectory(vendor/gns EXCLUDE_FROM_ALL)
  target_sources(forge_network PRIVATE engine/src/network_sockets.cpp)
  set_source_files_properties(engine/src/network_sockets.cpp PROPERTIES INCLUDE_DIRECTORIES "${CMAKE_CURRENT_SOURCE_DIR}/vendor/gns/include")
  target_link_libraries(forge_network PUBLIC GameNetworkingSockets_s)
endif()
if(FORGE_WITH_STEAMWORKS)
  if(NOT EXISTS "${FORGE_STEAMWORKS_SDK}/public/steam/steam_api.h")
    message(FATAL_ERROR "Set FORGE_STEAMWORKS_SDK to your official SDK; Forge does not download it")
  endif()
  if(WIN32)
    if(NOT CMAKE_SIZEOF_VOID_P EQUAL 8)
      message(FATAL_ERROR "Steamworks requires the supported 64-bit Forge build")
    endif()
    set(FORGE_STEAM_LIBRARY "${FORGE_STEAMWORKS_SDK}/redistributable_bin/win64/steam_api64.lib")
    set(FORGE_STEAM_RUNTIME "${FORGE_STEAMWORKS_SDK}/redistributable_bin/win64/steam_api64.dll")
  elseif(APPLE)
    set(FORGE_STEAM_LIBRARY "${FORGE_STEAMWORKS_SDK}/redistributable_bin/osx/libsteam_api.dylib")
    set(FORGE_STEAM_RUNTIME "${FORGE_STEAM_LIBRARY}")
  else()
    message(FATAL_ERROR "Forge Steamworks builds currently target macOS and Windows")
  endif()
  if(NOT EXISTS "${FORGE_STEAM_LIBRARY}" OR NOT EXISTS "${FORGE_STEAM_RUNTIME}")
    message(FATAL_ERROR "Steamworks runtime/library missing in SDK")
  endif()
  target_sources(forge_network PRIVATE engine/src/network_steam.cpp)
  set_source_files_properties(engine/src/network_steam.cpp engine/src/steam.cpp PROPERTIES INCLUDE_DIRECTORIES "${FORGE_STEAMWORKS_SDK}/public")
  target_link_libraries(forge_network PUBLIC "${FORGE_STEAM_LIBRARY}")
endif()
